- name: C/C++ Linter
  uses: cpp-linter/cpp-linter-action@83254e81a47b955a321f1831328e76e735ce8f04
  with:
    thread-comments: 'false'  # Change to 'true', 'false', or 'update' as needed
    no-lgtm: 'true'  # Change to 'true' or 'false' as needed
    step-summary: 'false'  # Change to 'true' or 'false' as needed
    file-annotations: 'true'  # Change to 'true' or 'false' as needed
    style: 'llvm'  # Change to your desired style, or use 'file' to use a .clang-format file
    extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'  # Modify as needed for your project
    tidy-checks: 'boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*'  # Modify as needed
    repo-root: '.'  # Modify if your repo root is different
    version: '12'  # Change to the clang version you want to use
    verbosity: 'info'  # Change the log verbosity if needed
    lines-changed-only: 'false'  # Change to 'true' or 'false' as needed
    files-changed-only: 'true'  # Change to 'true' or 'false' as needed
    ignore: '.github'  # Modify as needed to ignore paths
    # Add other options like 'database', 'extra-args', 'tidy-review', 'format-review' as needed
